version: '3.3'
services:
  frntend:
    build:
      context: ./
      dockerfile: ./docker/frntend/Dockerfile
    volumes:
      - ./:/home/repo
    container_name: frntend
    environment:
      BACKEND_ADDR: http://backend:3000
    ports:
      - "80:80"
      - "443:443"
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./:/home/repo
    ports:
      - "3000:3000"
      - "7000:7000"
    container_name: backend
